### ISSUE TITLE
esptouch.jar是乐鑫官方提供的吗？还是你自己封装的呢？

### ISSUE THREAD

**Issue by lianghuiyuan** [xumingxin7398/cordovaEsptouch#1]
你好，我最近也在研究esp8266的smartconfig功能，正想写一个Cordova插件时，发现了你写的这个插件，想咨询你一下：你插件里面的esptouch.jar是乐鑫官方提供的吗？还是你自己封装的呢？
因为如果我要把支持IOS做进去的话，IOS是否有类似esptouch.jar的库文件？或者是说我可以借鉴哪份资料做到这个库文件？非常感谢你的分享..。

**Comment by xumingxin7398** [comment]
自己封装的，ios版也封装了，晚点会提交上来。

**Comment by lianghuiyuan** [comment]
好的，非常感谢，期待iOS版本更新.
