### ISSUE TITLE
添加控件后，IOS编译出错

### ISSUE THREAD

**Issue by lianghuiyuan** [xumingxin7398/cordovaEsptouch#2]
你好，添加控件后，android上工作的很好，但是在IOS上，添加控件后便编译不通过了，具体错误如下：

ld: warning: ignoring file HelloWorld/Plugins/com.icubespace.cordova_esptouch/Esptouch.framework/Esptouch, file was built for armv7 which is not the architecture being linked (i386):     HelloWorld/Plugins/com.icubespace.cordova_esptouch/Esptouch.framework/Esptouch
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_ESPTouchTask", referenced from:
      objc-class-ref in esptouchPlugin.o
  "_OBJC_CLASS_$_ESP_NetUtil", referenced from:
      objc-class-ref in esptouchPlugin.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

The following build commands failed:
    Ld build/emulator/HelloWorld.app/HelloWorld normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Volumes/creasy/Projects/SVN/cordova/HelloWorld/platforms/ios/cordova/build-debug.xcconfig,-project,HelloWorld.xcodeproj,ARCHS=i386,-target,HelloWorld,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Volumes/creasy/Projects/SVN/cordova/HelloWorld/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Volumes/creasy/Projects/SVN/cordova/HelloWorld/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Volumes/creasy/Projects/SVN/cordova/HelloWorld/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Volumes/creasy/Projects/SVN/cordova/HelloWorld/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/Users/lianghuiyuan/nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by xumingxin7398** [comment]
因为我打包Esptouch.framework的时候没有添加i386这个平台，i386是专门给ios模拟器用的。因为模拟器上是无法使用SmartConfig这个功能的，所以你要测试这个功能的话，请用真机调试，ios打包的时候请在Build Settings里面把Architectures中的模拟器平台去掉。

**Comment by lianghuiyuan** [comment]
![f1a24e4b-6bf8-4178-95b0-26772d2667f7](https://cloud.githubusercontent.com/assets/8090998/11526223/f67606f8-9913-11e5-88d6-eda256f43ed5.png)

你好，我是用真机调试，不过我发现我的Architectures里面是没有i386的，能过编译build成功，却在App启动的时候报错，报错信息为：
(lldb)
error: No auto repeat.
dyld: Library not loaded: @rpath/Esptouch.framework/Esptouch
  Referenced from: /private/var/mobile/Containers/Bundle/Application/DB148427-0C9C-4F5E-AD96-E70585C01F5D/HelloWorld.app/HelloWorld
  Reason: image not found
Process 224 stopped
- thread #1: tid = 0x9808, 0x1feea08c dyld`dyld_fatal_error, stop reason = EXC_BREAKPOINT (code=EXC_ARM_BREAKPOINT, subcode=0xe7ffdefe)
  frame #0: 0x1feea08c dyld`dyld_fatal_error
  dyld`dyld_fatal_error:
  ->  0x1feea08c <+0>: trap
  0x1feea090 <+4>: nop

dyld`gdb_image_notifier:
    0x1feea094 <+0>: bx     lr

dyld`dyldbootstrap::start:
    0x1feea098 <+0>: push   {r4, r5, r6, r7, lr}
(lldb)
error: No auto repeat.

以下是项目工程中插件的.m文件和.framework文件：

![a69e9a5c-90f8-44da-8930-5810d156d5c4](https://cloud.githubusercontent.com/assets/8090998/11526832/2a3685ea-9918-11e5-851f-2bd86a97895e.png)

**Comment by xumingxin7398** [comment]
这个是ios开发常见的问题，你在Build Phases->Embed Frameworks里面把Esptouch.framework加进来即可。如果发布的时候再报错，可能是你的Link Binary With Libraries和Embed Frameworks存在重复的framework。

**Comment by lianghuiyuan** [comment]
非常感谢。你的控件用起来很不错。这个问题同时参考了http://www.ithao123.cn/content-3007257.html
把Esptouch.framework同时添加到‘TARGETS->General->Embedded Binaries’中即可。
