### ISSUE TITLE
[IOS]smartconfig 配置慢发现的问题

### ISSUE THREAD

**Issue by lianghuiyuan** [xumingxin7398/cordovaEsptouch#3]
不好意思，还有一个问题打扰你一下，在IOS端使用你的插件，从开发板端的调试日志看应该是smartconfig配置上了，但是从app的调试信息看好像有问题，有两个问题：1. app的日志不正常；2. 打调试信息“ESPTouchTask __execute() send gc code”时很慢，app此时应该处于等待状态，给用户感觉配置需要比较长的时间（10s+）。
根据我调试信息观察，打出调试信息“ESPTouchTask __execute() send gc code”时smartconfig其实是已经配置成功了.但app给用户的感觉还是在配置状态。此问题我猜在android上也有，因为我在调试android的时候smartconfig成功后到我我能过发出udp广播数据的过程比较长，中间有10s以上等待时间，但因为我android端环境的问题没法调试。
运行环境：iPhone4s    IOS8.4 
以下是App端调试信息：
（此问题在乐鑫官网貌似也有人遇到了：http://bbs.espressif.com/viewtopic.php?t=1414）

> 2015-12-03 22:25:36.915 HelloWorld[667:172745] THREAD WARNING: ['WifiWizard'] took '24.667969' ms. Plugin should use a background thread.
> 2015-12-03 22:25:50.375 HelloWorld[667:172745] ESPTouchTask init
> 2015-12-03 22:25:50.387 HelloWorld[667:172745] ##########################client init() _sck_fd=18
> 2015-12-03 22:25:50.390 HelloWorld[667:172745] ##########################server init(): _sck_fd=19
> 2015-12-03 22:25:50.397 HelloWorld[667:172745] ESP_NetUtil:: 192.168.0.102
> 2015-12-03 22:25:50.398 HelloWorld[667:172745] ESPTouchTask executeForResult() localInetAddr: 192.168.0.102
> 2015-12-03 22:25:50.408 HelloWorld[667:172745] ESPTouchTask __execute() send gc code 
> 2015-12-03 22:25:50.408 HelloWorld[667:173008] ESPTouchTask beginBackgroundTask() entrance
> 2015-12-03 22:25:50.412 HelloWorld[667:173008] ESPTouchTask __listenAsyn() start an asyn listen task, current thread is: <NSThread: 0x1777f010>{number = 7, name = (null)}
> 2015-12-03 22:25:50.413 HelloWorld[667:173008] ESPTouchTask __listenAsyn() expectOneByte: 30
> 2015-12-03 22:25:56.422 HelloWorld[667:172745] ESPTouchTask __execute() send gc code 
> 2015-12-03 22:26:02.423 HelloWorld[667:172745] ESPTouchTask __execute() send gc code 
> 2015-12-03 22:26:08.423 HelloWorld[667:172745] ESPTouchTask __execute() send gc code 
> 2015-12-03 22:26:14.455 HelloWorld[667:172745] ESPTouchTask __execute() send gc code 
> 2015-12-03 22:26:20.465 HelloWorld[667:172745] ESPTouchTask __execute() send gc code 
> 2015-12-03 22:26:26.465 HelloWorld[667:172745] ESPTouchTask __execute() send gc code 
> 2015-12-03 22:26:32.468 HelloWorld[667:172745] ESPTouchTask __execute() send gc code 
> 2015-12-03 22:26:35.418 HelloWorld[667:172745] ESPTouchTask __sleep() start
> server: receiveOneByte fail
> : Resource temporarily unavailable
> 2015-12-03 22:26:50.417 HelloWorld[667:173008] ESPTouchTask __listenAsyn() receive rubbish message, just ignore
> 2015-12-03 22:26:50.421 HelloWorld[667:172745] ESPTouchTask __sleep() end, receive signal is NO
> 2015-12-03 22:26:50.422 HelloWorld[667:172745] ###################server close() fd=19
> server: receiveOneByte fail
> : Bad file descriptor
> 2015-12-03 22:26:50.423 HelloWorld[667:173008] ESPTouchTask __listenAsyn() receive rubbish message, just ignore
> 2015-12-03 22:26:50.424 HelloWorld[667:172745] ESPTouchTask __notify()
> 2015-12-03 22:26:50.425 HelloWorld[667:173008] ESPTouchTask __notify()
> 2015-12-03 22:26:50.425 HelloWorld[667:172745] THREAD WARNING: ['esptouchPlugin'] took '60060.113037' ms. Plugin should use a background thread.
> 2015-12-03 22:26:50.425 HelloWorld[667:173008] ESPTouchTask __listenAsyn() finish
> 2015-12-03 22:26:50.427 HelloWorld[667:173008] ESPTouchTask endBackgroundTask() entrance
> 2015-12-03 22:26:50.430 HelloWorld[667:172869] void SendDelegateMessage(NSInvocation *): delegate (webView:decidePolicyForNavigationAction:request:frame:decisionListener:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode

**Comment by xumingxin7398** [comment]
这个问题可能跟参数taskResultCountStr有关，你可以下载一个官方的smartConfig的esptouch应用试一下：https://github.com/EspressifApp/EsptouchForIOS。当参数taskResultCountStr大于1，而实际附近能找到的设备数只有1个的时候，esptouch会继续查找，直到超时。所以参数taskResultCountStr恰好等于实际附近的设备数时，查找时间最短。

**Comment by pineson** [comment]
你好，很高兴发现有这个plugin，可是我无法在ios上编译通过，
ld: warning: ignoring file MyApp/Plugins/com.icubespace.cordova_esptouch/Esptouch.framework/Esptouch, file was built for armv7 which is not the architecture being linked (arm64): MyApp/Plugins/com.icubespace.cordova_esptouch/Esptouch.framework/Esptouch
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ESPTouchTask", referenced from:
      objc-class-ref in esptouchPlugin.o
  "_OBJC_CLASS_$_ESP_NetUtil", referenced from:
      objc-class-ref in esptouchPlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
能建议iOS上怎样编译吗？

**Comment by pineson** [comment]
solved， thanks

**Comment by mogupta** [comment]
Please share the solution ???
